// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoEZQgBFh59gJdfst51nBDATBGSzjOazM',
    appId: '1:15229256915:web:9e7d8b5735510d83f18026',
    messagingSenderId: '15229256915',
    projectId: 'we-chat-2cea4',
    authDomain: 'we-chat-2cea4.firebaseapp.com',
    storageBucket: 'we-chat-2cea4.firebasestorage.app',
    measurementId: 'G-DR9B6BRNWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKIXst8WTNbB9L9kZ_rpBPaxmAYzJ_-Q',
    appId: '1:15229256915:android:d96b2c2265ada2f0f18026',
    messagingSenderId: '15229256915',
    projectId: 'we-chat-2cea4',
    storageBucket: 'we-chat-2cea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzRly7PnrYNq2nkwcz5UIZlKFGzuQGgyk',
    appId: '1:15229256915:ios:af0d6ae730a248d3f18026',
    messagingSenderId: '15229256915',
    projectId: 'we-chat-2cea4',
    storageBucket: 'we-chat-2cea4.firebasestorage.app',
    androidClientId: '15229256915-ub1r54cqihnf3ftgv3ln5df60plem6tt.apps.googleusercontent.com',
    iosClientId: '15229256915-9hopc3lu8e9vrfq3562ir16pi66arbl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD55k6WahW03sa1CVG88em6NTuos-COtWY',
    appId: '1:15229256915:web:310572374bc1a02ef18026',
    messagingSenderId: '15229256915',
    projectId: 'we-chat-2cea4',
    authDomain: 'we-chat-2cea4.firebaseapp.com',
    storageBucket: 'we-chat-2cea4.firebasestorage.app',
    measurementId: 'G-3X29ZD8W7K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzRly7PnrYNq2nkwcz5UIZlKFGzuQGgyk',
    appId: '1:15229256915:ios:af0d6ae730a248d3f18026',
    messagingSenderId: '15229256915',
    projectId: 'we-chat-2cea4',
    storageBucket: 'we-chat-2cea4.firebasestorage.app',
    androidClientId: '15229256915-ub1r54cqihnf3ftgv3ln5df60plem6tt.apps.googleusercontent.com',
    iosClientId: '15229256915-9hopc3lu8e9vrfq3562ir16pi66arbl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

}