// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9OoBYEir8Jk4QKBn8npJfiuzf4cAj03o',
    appId: '1:906944702240:web:2128dbab935f84b9109945',
    messagingSenderId: '906944702240',
    projectId: 'ecommerce-1be89',
    authDomain: 'ecommerce-1be89.firebaseapp.com',
    storageBucket: 'ecommerce-1be89.firebasestorage.app',
    measurementId: 'G-PFD3VM34J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnKVIwrgG-7IDHP_D2OWvw_Ahu-epyf8',
    appId: '1:906944702240:android:643c9f3631887bca109945',
    messagingSenderId: '906944702240',
    projectId: 'ecommerce-1be89',
    storageBucket: 'ecommerce-1be89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZpCCgKVZr70Itr3aM_MbuzSy5sMvINJM',
    appId: '1:906944702240:ios:9f008fbb9b099337109945',
    messagingSenderId: '906944702240',
    projectId: 'ecommerce-1be89',
    storageBucket: 'ecommerce-1be89.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9OoBYEir8Jk4QKBn8npJfiuzf4cAj03o',
    appId: '1:906944702240:web:e810a16f9a420f7e109945',
    messagingSenderId: '906944702240',
    projectId: 'ecommerce-1be89',
    authDomain: 'ecommerce-1be89.firebaseapp.com',
    storageBucket: 'ecommerce-1be89.firebasestorage.app',
    measurementId: 'G-6GJ4NXDSWB',
  );
}
